### ISSUE TITLE
Wrongly listed under the KDE\Plasma store

### ISSUE THREAD

**Issue by maxiride** [ddnexus/Flat-Plat-Equilux#1]
I found this theme in the Discovery app of KDE Neon and I loved it! Too bad I think it's an errore since it's a GNOME theme :(

https://store.kde.org/p/1182169

**Comment by ddnexus** [comment]
Sorry, but I have no idea about how the themes get listed in that store, and whether I might have any control on that. It looks to be a non-issue in the context of the equilux-theme. Any suggestions?

**Comment by maxiride** [comment]
@ddnexus the only thing I could say is that it would be awesome to have a port for KDE DE! *:* =)

**Comment by ddnexus** [comment]
Thanks! :)
