### ISSUE TITLE
HexChat difficult to use with equilux

### ISSUE THREAD

**Issue by davidwords** [ddnexus/Flat-Plat-Equilux#10]
- Equilux = v20171120
- GTK+ 3 = 3.22.25
- Distribution (and version) = Ubuntu 17.10 (artful)
- Desktop environment (and version) = Gnome 3.26.2
- Related application (and version) = HexChat 2.12.4
- Steps to reproduce: Apply equilux (narrow) theme with Tweaks; run hexchat

![hexchat](https://user-images.githubusercontent.com/1211551/33862351-4a82c75c-deb0-11e7-92dd-a85e5e32e867.png)

As the screenshot shows, some of the app is unthemed, and two elements, the text box at bottom, and the channel box at top, have text foreground that's too close to the bg colour.

Thank you, by the way, for your work on this excellent theme.

**Comment by ddnexus** [comment]
Thanks for the feedback. It looks like the app doesn't use the GTK defaults provided by the theme, but hard-codes its own background colors. Not sure that it would be possible style it from the outside. However this is an upstream problem as well, and it should be addressed [upstream](https://github.com/nana-4/materia-theme/issues) 
(FYI: @nana-4)

**Comment by nana-4** [comment]
Yeah, it seems HexChat doesn't use the system (GTK) colors, but instead uses its [own themes](https://hexchat.readthedocs.io/en/latest/appearance.html) to control colors.

You can change the colors via **Settings ‣ Preferences ‣ Colors**, but I may provide HexChat theme(s) according to the GTK theme color scheme.

**Comment by davidwords** [comment]
Thanks for the attention, @ddnexus and @nana-4. 

I tried a couple of the hexchat themes and found that the one called Zenburn dovetails nicely with Equilux. Perhaps it could be bundled with it (or with Materia).

![vlc](https://user-images.githubusercontent.com/1211551/34002295-35b7ae8e-e0c0-11e7-9f2c-a0cdc647075a.png)

**Comment by ddnexus** [comment]
Just released a new version, and I found to mention this theme... :/
 Pushed to WIP: it will go into the next release. Closing the issue.
