### ISSUE TITLE
Don't even show up

### ISSUE THREAD

**Issue by ghost** [ddnexus/Flat-Plat-Equilux#12]
In GNOME Shell 3.26 the theme doesn't even show up in gnome-tweak-tool.

**Comment by ddnexus** [comment]
I have GNOME Shell 3.26.2 and I can assure you it does show up! :)

There are a number of things that you should check, the most obvious:

1. the User Themes Extension must be enabled
2.  `usr/share/themes/Equilux` and/or `/usr/share/themes/Equilux-compact` dirs are present and populated with the needed files

How did you install?

**Comment by ghost** [comment]
Thought open-desktop.org. I will try a git clone

**Comment by ddnexus** [comment]
You can just download from  open-desktop.org the equilux-theme-v20180110.tar.xz unzip and move the 2 dirs into `/usr/share/themes`.

**Comment by ghost** [comment]
Yep it works, but Firefox bookmarks are invisible (dark over dark) :(

![screenshot from 2018-01-29 11-10-25](https://user-images.githubusercontent.com/1469713/35505056-2228a51e-04e5-11e8-94e6-c31a268a58a2.png)

**Comment by ghost** [comment]
OK it was just necessary to close and reopen it. Thanks!
