### ISSUE TITLE
[suggestions] recommended icons and terminal scheme

### ISSUE THREAD

**Issue by ghost** [ddnexus/Flat-Plat-Equilux#13]
Hello, hope you're fine.

I would like to suggest two things that you could add in readme file as recommended extras.

1 - [**Zafiro icons**](https://github.com/zayronxio/Zafiro-icons) - a new icon theme fitting Equilux perfectly - screenshots 1 & 2 - by @zayronxio

2 - [**Smyck terminal**](https://github.com/DarthWound/smyck-gnome-terminal) - a script to use smyck palette in GNOME Terminal - screenshot 3 - by me and @hukl

![capture d ecran de 2018-01-30 02-42-06](https://user-images.githubusercontent.com/1771322/35543842-a5342a28-0567-11e8-8a29-438a58ecee9c.png)
![capture d ecran de 2018-01-30 02-42-13](https://user-images.githubusercontent.com/1771322/35543843-a54f85ca-0567-11e8-93cf-1ca2acce3300.png)
![capture d ecran de 2018-01-30 02-44-40](https://user-images.githubusercontent.com/1771322/35543844-a56a67c8-0567-11e8-9820-c0cd1661f69f.png)

**Comment by ddnexus** [comment]
Nice! Thank you! Could just edit the README and create a PR? Thanks.

**Comment by ghost** [comment]
PR https://github.com/ddnexus/equilux-theme/pull/14
