### ISSUE TITLE
White border + no close button at the top of window manager theme (in dialog boxes)

### ISSUE THREAD

**Issue by chuutatsu** [ddnexus/Flat-Plat-Equilux#16]
Glad there was a dark flat like this Equilux! I really enjoyed using it however...

I found out that some small dialog boxes (like below images) has white border on the top of its window manager. It also has no close window button. I am using Mate Desktop 1.18 and GTK 3.

![screenshot at 2018-02-15 07-55-34](https://user-images.githubusercontent.com/24815847/36235991-401384f6-1226-11e8-91c5-4793c34e1b50.png)
![screenshot at 2018-02-15 07-59-37](https://user-images.githubusercontent.com/24815847/36235992-40501dbc-1226-11e8-8613-0d9e4ebf45f3.png)

Please fix this and thanks!

**Comment by ddnexus** [comment]
Please, could you install the [Materia](https://github.com/nana-4/materia-theme) theme (the upstream project) e see if it has the same problem. If that is the case, please, report the problem [here](https://github.com/nana-4/materia-theme/issues). In any case, please, let me know.

**Comment by chuutatsu** [comment]
I checked the latest Materia and apparently it was also appeared in the dark version. I'll close this thread since I have reported the problem there.
