### ISSUE TITLE
se ve oscuro en caja de texto en firefox, por ejemplo en el buscardor el fondo es oscuro al igual de las letras 

### ISSUE THREAD

**Issue by jsdextre** [ddnexus/Flat-Plat-Equilux#17]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Distribution (and version)
- Desktop environment (and version)
- Related application (and version)
- Steps to reproduce
- Screenshot(s)

**Comment by jsdextre** [comment]
hola amigo gracias por responder, no te preocupes que tambien entiendo ingles, yo sé aqu te referias pero pense que te habias equibocado pero bueno el punto es que el tema oscuro en gnome de Fedora 27 se ve muy bien pero cuando uso firefox muchas paginas las cajas de texto se ven oscuros al igual que el color de las letras, por ejemplo en youtube casi no se ven las letras en la caja de busqueda y lo mismo sucede en varias páginas, no crees que tu tema no debería tocar firefox ó solamente en la parte de arriva algo asi como lo hace numix, gracias por tiempo lo aprecio mucho. saludos desde Lima Perú
Fedora 27 con Gnome 3.28

**Comment by ddnexus** [comment]
OK. Pues necesito algunas cosas:
1. carga uno screenshot aquí, donde se ve bien lo que describes con el Equilux
2. Instala [Materia Theme](https://github.com/nana-4/materia-theme), y prueba la version oscura (dark).
3. carga uno screenshot tanbién de como se ve con Materia-dark.
Gracias

**Comment by jsdextre** [comment]
hola amigo ya he instalado Materia Theme dark y esta peor ahora no se ven nada en la caja de busqueda en youtube, y lo mismo la caja de texto se ve oscuro en firefox y la letras negras, y dime una cosa con todo respeto cuando tu usas tu tema oscuro, tu no te das cuenta que las letras no se ven cuando escribes en las paginas web? o talvez tu estas haciendo algo que yo no sé talvez usas alguna extención para firefox?, talvez alguna extención de gnome-shell? o talvez deberías no tocar a firefox en los temas que haces, tu que pienzas? gracias amigo por tu tiempo pero disculpame por seguir con este tema dejemoslo asi talvez estaré haciendo algo mal. gracias y saludos

**Comment by ddnexus** [comment]
Hola. Te agradezco de que te preocupes por mi tiempo, pero, no quiero "dejarlo así" porque si es un problema de mi tema tengo que resolverlo, si es un problema con Materia (upstream) su autor tiene que resolverlo, y si es un problema con tú Firefox, quiero saber lo que es y ayudarte a resolverlo.

Te pregunté por los screenshots, porque no entiendo a que te refieres cuando hablas de la "caja de busqueda". Si te refieres a parte de la aplicación (al rededor de la pagina pero no adentro de la pagina) es un problema del tema, si esta en la pagina, pues quizas tienes instalada alguna extension que cambia el estilo de la pagina.

Aqui esta mi screenshot de YouTube en Firefox (que instalé justo ahora para darme cuenta si tiene un problema)... pero me parece que todo esta bien. 

![screenshot from 2018-02-19 13-53-20](https://user-images.githubusercontent.com/100721/36365672-227531d8-157d-11e8-854e-967b948944b1.png)

Por favor puedes ponerme la imagen de lo que pasa en tu Firefox? Seria muy util. Gracias.

**Comment by jsdextre** [comment]
![captura de pantalla de 2018-02-19 02-16-53](https://user-images.githubusercontent.com/25498335/36366211-19d2e316-151b-11e8-8029-c551d124d239.png)
![captura de pantalla de 2018-02-19 02-14-58](https://user-images.githubusercontent.com/25498335/36366224-28a073cc-151b-11e8-9e17-be954ec2878a.png)
![captura de pantalla de 2018-02-19 02-14-33](https://user-images.githubusercontent.com/25498335/36366238-3029713e-151b-11e8-9e0f-e1b99fe7f89e.png)
 aqui estan algunas tomas usando firefox quantum en fedora 27 con su tema normal de firefox

**Comment by jsdextre** [comment]
en la primera imagen te estoy ecribiendo pero no se nota las letras en gnome-look, en la segunda imagen estoy haciendo una búsqueda en youtube y las letras casi ni se ven y en la tercera no se ven las letras porque el fondo es oscuro y las letras tambien. gracias

**Comment by jsdextre** [comment]
![captura de pantalla de 2018-02-19 02-25-24](https://user-images.githubusercontent.com/25498335/36366453-2fe08cac-151c-11e8-9f82-397537c3b5aa.png)
hola amigo puedes acerlo asi como en numix solo oscurece la barra de arriba de las pestañes de las paginas sin tocar el resto de firefox

**Comment by ddnexus** [comment]
Gracias! Eso si fue útil! Ahora está claro! Pues, no... el texto está oscuro todavía, pero esta claro que esta oscuro! Jajaja...

El problema no está en tu FF: aquí se ve mal de la misma manera. Yo no cambié nada para FF en Equilux, asi que el problema probablemente está en Materia (que me dijiste se ve aún peor). Si ya no esta resuelto, voy a reportar el problema upstream. Si esta resuelto upstream, voy a incluir el fix en Equilux lo más pronto posible. 

Muchísima gracias por tu colaboración! Voy a tener ese "issue" abierto así que vas a enterarte de cuando se va a resolver.

**Comment by jsdextre** [comment]
espera no te vayas aun, una pregunta ahy un equipo llamado upstream que hace Materia? y como otros como numix por ejemplo no sucede no crees que no deberían tocar firefox ya que firefox tiene su propio tema oscuro, ahora esto mezclado con un tema oscuro de gnome mas algun tema de firefox es una tortura para los ojos. bueno espero lo tomes de  la mejor manera, gracias y saludos.

**Comment by ddnexus** [comment]
"upstream" quiere decir que esta "a la fuente". Equilux es derivado desde Materia... es decir que es una modificación de Materia, o sea el 90% es materia, y el 10% son los cambios que lo hacen diferente de Materia. En ese caso upstream es como decir "el original que esta a la fuente de Equilux". Los problemas pueden estar en el 90% upstream o en el 10% de Equilux. En ese caso es muy facil que estén en el 90% upstream.

**Comment by ddnexus** [comment]
https://github.com/nana-4/materia-theme/issues/205

**Comment by ddnexus** [comment]
@jsdextre Reporté el problema upstream y parece que no es nisiquiera un problema de Materia: es un problema de Adwaita (el upstream de Materia). Puedes averiguarlo probando el Adwaita Dark con tu Fedora. Deberia de tener el mismo problema de Materia y de Equilux. Si puedes averiguarlo, por favor repórtalo aqui. Gracias.

**Comment by ddnexus** [comment]
... y acabo de descubrir que es un bug en Firefox!!!

https://bugzilla.mozilla.org/show_bug.cgi?id=519763

en la pagina están algunas posible soluciones.

**Comment by ddnexus** [comment]
esta es una solución simple que resuelve el bug de Firefox, y permite de usar todos los temas "dark" (la probé ahora y funciona):

Añada esta linea:

```CSS
input, textarea { color: #222; background: #eee; }
```

en el archivo `<your firefox profile dir>/chrome/userContent.css` (crea el archivo si no está).

**Comment by jsdextre** [comment]
hello friend thank you for your answer but tell me where i must write that
line? can you tell me what is the path? thank you

Jenrry Soto Dextre
Cel: (51) 970954819
E-mail:          dextre1480@gmail.com
Página web:   www.dextreart.com
Página Web:  dextre.artelista.com
Facebook:     arte pinturas dextre

El 20 de febrero de 2018, 20:46, Domizio Demichelis<notifications@github.com

**Comment by ddnexus** [comment]
The profile dir is different for your profile, however you should find it at:

`/home/$USER/.mozilla/firefox/<a_weird_id>`

The `<a_weird_id> ` should look like `i3l7bmma.default-1519023165734`. That is the profile dir... so inside that there is a `chrome`  dir... if it is not there create it. Then inside it there shouuld be `userContent.css`... if it is not there you create it... and inside that file you should write the line.

**Comment by jsdextre** [comment]
helllo friend I have 4 things Crash Rpots, nphves22.default, Pending Pings,
profile.ini  wich of them i must add the line?

Jenrry Soto Dextre
Cel: (51) 970954819
E-mail:          dextre1480@gmail.com
Página web:   www.dextreart.com
Página Web:  dextre.artelista.com
Facebook:     arte pinturas dextre

2018-02-21 0:19 GMT-05:00 Domizio Demichelis <notifications@github.com>:

**Comment by ddnexus** [comment]
`nphves22.default/chrome/userContent.css`

**Comment by jsdextre** [comment]
I added a file called  userContent.css  and inside this i wrote

input, textarea { color: #222; background: #eee; }

and ready, now let me try

Jenrry Soto Dextre
Cel: (51) 970954819
E-mail:          dextre1480@gmail.com
Página web:   www.dextreart.com
Página Web:  dextre.artelista.com
Facebook:     arte pinturas dextre

2018-02-21 0:42 GMT-05:00 Jenrry Dextre <dextre1480@gmail.com>:
