### ISSUE TITLE
Title is too bright

### ISSUE THREAD

**Issue by chuutatsu** [ddnexus/Flat-Plat-Equilux#18]
![screenshot at 2018-02-20 17-47-03](https://user-images.githubusercontent.com/24815847/36419978-15fe51e8-1666-11e8-924f-42d095d974a8.png)

Compared to the Equilux screenshots (I knew it was Gnome screenshot) and Xfwm4 theme, the title color in Mate  was too bright and not matched with the rest of neutral colors. Is this intentional or not?

I am using Mate 1.20, GTK 3.22 and latest Equilux.

**Comment by ddnexus** [comment]
Not intentional at all! Sorry. I don't have any Mate installed, so I am a bit blind about it. Your report is very useful. I will take a better look at it in the next release.... I have to halt it for a few days because I am busy with another project.

Meanwhile, please, could you check every possible inconsistency and add more screenshots here? It would be really useful if you could add more context around the problem (i.e. wider screenshot view with other element), eventually highlighting the problem with an arrow or something in the screenshot itself.

Thank you!

**Comment by chuutatsu** [comment]
Alright it's fine! I will wait until the next bugfix.

This is how Equilux's window manager theme looked like in Xfwm (notice the darker grey title color):
![screenshot at 2018-02-20 19-30-26](https://user-images.githubusercontent.com/24815847/36424353-922194ba-1675-11e8-8d3f-d5ee2e7e3e71.png)

Meanwhile, this is how it looked like in Marco (MATE's WM):
![screenshot at 2018-02-20 19-28-50](https://user-images.githubusercontent.com/24815847/36424411-c92fdf48-1675-11e8-9020-9af965547698.png)

As you can see, the title font in Xfwm was darker grey. While the title font in Marco was too bright.

**Comment by ddnexus** [comment]
That is really useful. Thank you!

**Comment by ddnexus** [comment]
I fixed some color... could you try this [wip-equilux.zip](https://github.com/ddnexus/equilux-theme/files/1862690/wip-equilux.zip) version?

**Comment by chuutatsu** [comment]
![screenshot at 2018-03-31 20-32-51](https://user-images.githubusercontent.com/24815847/38163734-0096748a-3523-11e8-919e-1ca182e236ae.png)

Apparently there is no much difference in the titlebars. It is still bright.

**Comment by ddnexus** [comment]
@nana-4: I didn't find anything related to the window title in the `_mate.scss` and it looks like Mate may use some different rule/naming for it. The color set in `_colors.scss` didn't get used for the window title in Mate. Did I miss something?

**Comment by nana-4** [comment]
@ddnexus Mate's default WM is Marco, forked from Metacity. So you can change the title color from [here](https://github.com/ddnexus/equilux-theme/blob/equilux-dev/src/metacity-1/metacity-theme-2.xml#L20-L21) (`#FFFFFF`). (FYI, Marco does not support `metacity-theme-3.xml` format at the moment.)

**Comment by ddnexus** [comment]
AHA! I knew that I missed something! LOL
@nana-4: Thank you so much!!! Your help is always great!

**Comment by ddnexus** [comment]
@chuutatsu: please, try the latest [release](https://github.com/ddnexus/equilux-theme/releases/tag/equilux-v20180406) and let me know if it is fixed. Thanks.

**Comment by chuutatsu** [comment]
Sorry for late reply! Here is the latest screenshot of Equilux's latest release:
![screenshot at 2018-04-16 23-35-20](https://user-images.githubusercontent.com/24815847/38822851-e4c9d2de-41ce-11e8-8c1d-e62536d11ce9.png)
The font color of the titlebar is darker and matched the darkness of "Administration" title. Thank you very much!
