### ISSUE TITLE
Just FYI: new Materia release with Gnome 3.28 support

### ISSUE THREAD

**Issue by aquatix** [ddnexus/Flat-Plat-Equilux#21]
Happily using this great theme on Gnome 3.26, but as Gnome 3.28 is out, I noticed that upstream Materia has an update for that new version. Just a heads-up :)

**Comment by ddnexus** [comment]
Yeah, I'm late.
I almost finished another project... and this will be next.
Thanks

**Comment by aquatix** [comment]
Oh, no worries, like said, just wanted to give a heads-up. Good luck with your projects and thanks again for this theme!
