### ISSUE TITLE
Color for on-off switches

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/Flat-Plat-Equilux#22]
@nana-4: It looks like the toggle-switches of settings and tweaks are not assets like the on/off toggles used in the menus for example. They get the colors from the `_colors.scss`, but I couldn't find the specific CSS rule that affects them exclusively. Do they have some class/classes that I could change arbitrarily, or do they use some other asset that I cannot find? Thanks.

**Comment by nana-4** [comment]
@ddnexus I'm sorry for the late reply. I'm not sure which "switches" you are talking about, but maybe [this](https://github.com/ddnexus/equilux-theme/blob/dfd791de91992786b1e1f692530d33f17729aea6/src/_sass/gtk/_common-3.20.scss#L2024-L2072) is it? If I'm wrong, please show me the switches with a screenshot. Thanks.

**Comment by ddnexus** [comment]
Thanks @nana-4! I was missing you!
Yes, even with my bad explanation you got it right. That is the switch I couldn't find. You are a savior as usual! Thank you!
