### ISSUE TITLE
Compact version vertical spacing

### ISSUE THREAD

**Issue by spsf64** [ddnexus/Flat-Plat-Equilux#25]
Can you make the compact version a bit more "dense" with less vertical space between the lines?
1st shot is equilux, second is adapta theme ETA (the compact version)
TIA

Equilux:
![equilux](https://user-images.githubusercontent.com/1877391/44432897-58404400-a57a-11e8-909d-18ef07b090e3.png)

Adapta:
![adapta](https://user-images.githubusercontent.com/1877391/44432915-6f7f3180-a57a-11e8-8318-445474322bc1.png)

**Comment by ddnexus** [comment]
I understand your request, and I even would prefer a bit more dense compact variant. However that is something decided upstream that is out of scope for Equilux. (please see the [Technical Focus](https://github.com/ddnexus/equilux-theme#technical-focus) in the README file)

You may want to post a request in the materia issues: if accepted/implemented there it will appear in Equilux as well.
