### ISSUE TITLE
Volume & brightness bars in system tray

### ISSUE THREAD

**Issue by millsp** [ddnexus/Flat-Plat-Equilux#27]
- Equilux version: [Git](https://github.com/ddnexus/equilux-theme/commit/6c1f7eab51d46d9c4583d19e9a44c646f72ff025)
- GTK+: 3.0
- Distribution: Ubuntu 18.04
- Desktop environment: Default
- Related application: System tray
- Steps to reproduce: Installed GDM
- Screenshot(s): [Screenshot](https://ibb.co/233513H)

**Comment by ddnexus** [comment]
Weird. I use Ubuntu 18.10 and it is OK. What shell version?

**Comment by millsp** [comment]
Gnome shell is 3.28.3. It's only in the system tray, it works very well everywhere else !
Can you please give me the css selector so I compare with the original ubuntu.css ?

**Comment by ddnexus** [comment]
No Idea about the CSS selector... I should search but I have no time now.

With that Ubuntu Version I was OK a few versions ago... probably around [equilux-v20180513](https://github.com/ddnexus/equilux-theme/releases/tag/equilux-v20180513).

If you have time to try that version, it would be a clue for when I will have the time to fix it. Thanks.

**Comment by millsp** [comment]
Worked! I replaced **Equilux/gnome-shell/gnome-shell.css** with **equilux-theme-equilux-v20180513/src/gnome-shell/3.28/gnome-shell-dark.css**.

Thanks for this awesome theme
