### ISSUE TITLE
Text unreadable in popup menus

### ISSUE THREAD

**Issue by jblaszczyk** [ddnexus/Flat-Plat-Equilux#30]
- Equilux version v20181029
- GTK+ 3 version 3.24.12-1ubuntu1
- Ubuntu 19.10
- stock GNOME 3.34
- the shell itself, popup menus

after installing the theme into `/usr/shell/themes` menu items (unhighlighted) in popups are barely visible due to dark text colors

![bad colors](https://user-images.githubusercontent.com/7831951/68594350-a26f5700-0497-11ea-8b03-2ca8291890f3.png)

**Comment by jblaszczyk** [comment]
easy fix is to add proper `color` property to popup items in `gnome-shell.css`:

```
    .popup-menu .popup-menu-item {
      spacing: 8px;
      transition-duration: 100ms;
      color: #bebebe;
    }
```


though other widgets like calendar, worldclocks etc also need fixing.

**Comment by ddnexus** [comment]
Thank you for the report... and for the fix :)
I suspect there are other glitches for 3.34, but I didn't have the time to try it.

**Comment by ddnexus** [comment]
Sorry for the late answer. I got some time to switch to Ubuntu 19.10 and found the problem...

It is actually the fact that "Ubuntu"session is not a proper "GNOME" session and it is [unsupported upstream](https://github.com/nana-4/materia-theme#unsupported). 

In the same linked paragraph is also indicated how to work around the issue, so I am going to close this issue.
