### ISSUE TITLE
Panel Indicator uses 25% cpu with equilux theme

### ISSUE THREAD

**Issue by psimacek** [ddnexus/Flat-Plat-Equilux#6]
Hi, 

I don't know exactly, if it's Materia or Equilux theme problem, but with eg. Arc theme this bug doesn't affects me. Problem is with xfce4-indicator-plugin. Details are here: 

https://bugs.launchpad.net/ubuntu/+source/xfce4-indicator-plugin/+bug/1583164

**Comment by ddnexus** [comment]
If I correctly understand the bug, then my guess is that also Adwaita should cause the same overhead (having gradient). Could you confirm that?

**Comment by psimacek** [comment]
No, with Adwaita it works as expected. Now I found, that the problem is causing xfce4-pulsaudio-plugin for me. If I remove it from panel, cpu goes down.

**Comment by ddnexus** [comment]
So it looks like the culprit is probably the combination of something else that is not under my control, right? If that is the case, please close this issue. Thanks.

**Comment by psimacek** [comment]
Yes, I agree, it's combination of something, but some themes are not affected.
