### ISSUE TITLE
Telegram theme

### ISSUE THREAD

**Issue by aquatix** [ddnexus/Flat-Plat-Equilux#7]
Let me start with giving you a big THANK YOU for this great theme! It's so nice and soothing on the eyes.

As I was tinkering with my desktop, I noticed that Telegram was looking off (because I did not have it in the right colours of this theme). Searching around I stumbled upon https://github.com/lkd70/Linux-Mint-Y-Dark-Telegram-Theme that at least resembles the colours of Equilux, but it's not entirely right.

I'm not sure if you even use Telegram, but could you look into making an Equilux theme? Otherwise I'll try my hand at it myself (maybe with some pointers about the exact colours).

Thanks in advance!

**Comment by aquatix** [comment]
Just a FYI that I tweaked the above mentioned theme a bit: https://github.com/aquatix/Equilux-Telegram-Theme

Still light green highlights, but that's OK with the rest of Equilux for the moment :)

**Comment by ddnexus** [comment]
I don't use it and honestly i didn't even know it exists, but it looks nice. You should go ahead and do it. ;) 

In order to pick the right colors you should look at a couple of files:
[Equilux Palette](https://github.com/ddnexus/equilux-theme/blob/equilux-dev/src/equilux/equilux-palette.scss)
[Equilux GTK3 Colors](https://github.com/ddnexus/equilux-theme/blob/equilux-dev/src/gtk-3.0/3.22/sass/_colors.scss)

I think I should open a section in the Readme collecting all the themes people do for particular apps. I have something (incomplete) for Tilix, RubyMine, SmartGit, DeepGit, ... I saw someone did a theme for VLC, now... Telegram.

**Comment by ddnexus** [comment]
@aquatix: your example theme link gives a Not Found error.

**Comment by aquatix** [comment]
That's a link originally from the other theme I forked it from. I'll create a new screenshot in a few hours.

**Comment by aquatix** [comment]
@ddnexus and indeed, having a bit of documentation might be enough, as you should not be the only one that everyone is looking at to create things :)

With palette info, others like me can help you out.

**Comment by aquatix** [comment]
Updated the README, now links to my gallery: https://shuttereye.org/various/screenshots/20171124_telegram_equilux.png/view/

**Comment by ddnexus** [comment]
It looks nice. When you will find a way to customize all the colors it will be great. 
FYI: Foreground color (e.g. text and icons) should never be brighter than #BEBEBE, but you probably already know that. :)

**Comment by aquatix** [comment]
Yeah, was already fixing that. Had not touched the greens, as it's quite integral to the original theme. Also, I'm a bit unsure about what to use as accent colour for the Equilux variant, if any. Think I'll go for the lighter brownish-grey of Equilux.

I have it currently looking like this:

![20171124_telegram_equilux_better](https://user-images.githubusercontent.com/629545/33212026-79891de0-d121-11e7-8332-96d82f11967c.png)

**Comment by ddnexus** [comment]
hmmm... it looks quite familiar now! :)

Just an idea that might not work on that particular layout: sometimes I use the window bar background (#373737) as the content background, so removing the different lighter gray (#414141) and creating a solid slate with less areas. Not sure that it wold be usable in that app though.

**Comment by aquatix** [comment]
I don't think I would like that; that way the left list will bleed too much into the conversation on the right, making it more noisy, I think.

I'll tinker a bit more with it this weekend, as there's still some green in it, but I like where this is going :)

**Comment by ddnexus** [comment]
Added a link in the readme

**Comment by cj-sv** [comment]
Heya @aquatix, hope you can update the theme preview in your Equilux-Telegram-Theme repo. I thought the accents were still green when I was checking it out.
